version: '3'

services:

  demo-db:
    image: containerregistrysauleaalessandro30242.azurecr.io/db
    deploy:
      resources:
        limits:
          cpus: '0.5'
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root"]
      timeout: 45s
      interval: 10s
      retries: 5
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=energy
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"

  demo-be:
    image: containerregistrysauleaalessandro30242.azurecr.io/be
    deploy:
      resources:
        limits:
          cpus: '0.5'
    restart: always
    ports:
      - "8080:8080"
    environment:
      #- DB_IP=172.22.0.2
      - DB_IP=demo-db
      - RABBIT_IP=demo-rabbit
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_DBNAME=energy
    depends_on:
      demo-db:
        condition: service_healthy
  
  demo-fe:
    image: containerregistrysauleaalessandro30242.azurecr.io/fe
    deploy:
      resources:
        limits:
          cpus: '0.5'
    restart: always
    ports:
      - "3000:3000"

  demo-mq:
    image: containerregistrysauleaalessandro30242.azurecr.io/mq
    deploy:
      resources:
        limits:
          cpus: '0.5'
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
